CREATE TABLE userinfo
(
    name               VARCHAR(255) NOT NULL,
    last_authorization VARCHAR(255),
    CONSTRAINT pk_userinfo PRIMARY KEY (name)
);

CREATE TABLE postinfo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content   VARCHAR(255),
    image     VARCHAR(255),
    time      VARCHAR(255),
    user_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_postinfo PRIMARY KEY (id)
);

ALTER TABLE postinfo
    ADD CONSTRAINT FK_POSTINFO_ON_USER_NAME FOREIGN KEY (user_name) REFERENCES userinfo (name);